name: Test
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    tags-ignore:
      - "**"
    branches:
      - main


jobs:
  psalm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0']
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - name: Cache Composer
        uses: actions/cache@v2
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - run: composer install
      - run: ./vendor/bin/psalm

  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0']
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: none
      - name: Cache Composer
        uses: actions/cache@v2
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - run: composer install
      - run: ./vendor/bin/phpunit tests --testdox
